
import React, { useState } from 'react';
import { IGCase, IGDocument, Communication, DocumentSection, ResponseStatus, CaseStatus } from '../types';
import { 
  ArrowLeft, FileText, MessageSquare, History, Users, 
  Plus, CheckCircle2, Clock, AlertTriangle, Printer, Trash2, ShieldAlert, Edit2, Save, Send, Building, StickyNote, FileCheck
} from 'lucide-react';
import { processLargeDocument } from '../services/geminiService';
import { CASE_STATUSES } from '../constants';

interface CaseDetailsProps {
  caseData: IGCase;
  onBack: () => void;
  onUpdate: (updatedCase: IGCase) => void;
}

const CaseDetails: React.FC<CaseDetailsProps> = ({ caseData, onBack, onUpdate }) => {
  const [activeTab, setActiveTab] = useState<'info' | 'documents' | 'reminders' | 'timeline' | 'officers'>('info');
  const [isProcessing, setIsProcessing] = useState(false);
  const [isAddingComm, setIsAddingComm] = useState(false);
  const [isEditingNotes, setIsEditingNotes] = useState(false);
  const [notesDraft, setNotesDraft] = useState(caseData.internalNotes);

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setIsProcessing(true);
    try {
      const { text, metadata, summary, sections } = await processLargeDocument(file);
      
      const newDoc: IGDocument = {
        id: Math.random().toString(36).substr(2, 9),
        type: 'Finance Letter',
        fileNumber: metadata.fileNumber,
        date: metadata.date,
        district: metadata.district,
        signingAuthority: metadata.authority,
        fileName: file.name,
        summary: summary,
        approved: false,
        ocrText: text,
        uploadDate: new Date().toISOString(),
        sections: sections
      };

      onUpdate({
        ...caseData,
        documents: [...caseData.documents, newDoc],
        timeline: [
          ...caseData.timeline,
          {
            id: Date.now().toString(),
            timestamp: new Date().toISOString(),
            action: `New Document Processed: ${file.name}`,
            remarks: 'Administrative summary generated by AI for Inspector General review.'
          }
        ]
      });
      setActiveTab('documents');
    } catch (err) {
      console.error(err);
    } finally {
      setIsProcessing(false);
    }
  };

  const updateCaseStatus = (newStatus: CaseStatus) => {
    onUpdate({
      ...caseData,
      status: newStatus,
      timeline: [
        ...caseData.timeline,
        {
          id: Date.now().toString(),
          timestamp: new Date().toISOString(),
          action: 'Status Change',
          oldStatus: caseData.status,
          newStatus: newStatus,
          remarks: `Administrative workflow transitioned to ${newStatus}.`
        }
      ]
    });
  };

  const handleSaveNotes = () => {
    onUpdate({
      ...caseData,
      internalNotes: notesDraft,
      timeline: [
        ...caseData.timeline,
        {
          id: Date.now().toString(),
          timestamp: new Date().toISOString(),
          action: 'Notes Updated',
          remarks: 'Internal administrative notes updated by system administrator.'
        }
      ]
    });
    setIsEditingNotes(false);
  };

  const handleAddCommunication = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const recipients = (formData.get('recipients') as string).split(',').map(s => s.trim());
    const type = formData.get('type') as any;
    
    // Auto-calculate reminder count
    let reminderCount = 0;
    if (type === 'Reminder 1') reminderCount = 1;
    if (type === 'Reminder 2') reminderCount = 2;
    if (type === 'Final Reminder') reminderCount = 3;

    const newComm: Communication = {
      id: Date.now().toString(),
      type: type,
      outgoingFileRef: formData.get('ref') as string,
      incomingFileRef: '',
      dateIssued: new Date().toISOString().split('T')[0],
      dueDate: formData.get('dueDate') as string,
      status: 'Awaiting',
      reminderCount: reminderCount,
      recipients: recipients,
      recipientCount: recipients.length
    };

    // Update case status if it's a reminder
    let nextStatus = caseData.status;
    if (type === 'Reminder 1') nextStatus = 'Reminder 1 issued';
    if (type === 'Reminder 2') nextStatus = 'Reminder 2 issued';
    if (type === 'Final Reminder') nextStatus = 'Final reminder issued';

    onUpdate({
      ...caseData,
      status: nextStatus,
      communications: [newComm, ...caseData.communications],
      timeline: [
        ...caseData.timeline,
        { id: Date.now().toString(), timestamp: new Date().toISOString(), action: `Correspondence Sent: ${type}`, remarks: `Official letter dispatched to ${recipients.join(', ')}.` }
      ]
    });
    setIsAddingComm(false);
  };

  const evaluateResponse = (commId: string, result: ResponseStatus) => {
    onUpdate({
      ...caseData,
      cooperative: result === 'Satisfactory',
      communications: caseData.communications.map(c => c.id === commId ? { ...c, status: result, receivedDate: new Date().toISOString().split('T')[0] } : c),
      timeline: [
        ...caseData.timeline,
        { id: Date.now().toString(), timestamp: new Date().toISOString(), action: 'Response Evaluated', remarks: `Incoming response marked as ${result}.` }
      ]
    });
  };

  const generateFinalReport = () => {
    const reportWindow = window.open('', '_blank');
    if (!reportWindow) return;

    const html = `
      <html>
      <head>
        <title>Final Case Report - ${caseData.id}</title>
        <script src="https://cdn.tailwindcss.com"></script>
        <style>@media print { .no-print { display: none; } }</style>
      </head>
      <body class="p-12 font-serif text-gray-900">
        <div class="max-w-4xl mx-auto border-4 border-emerald-900 p-8 relative">
          <div class="flex justify-between items-start mb-8 border-b-2 border-gray-200 pb-6">
            <div class="w-24 h-24 flex items-center justify-center p-2 border bg-gray-50 text-[10px] font-bold text-center uppercase text-gray-400">
              OFFICIAL CREST
            </div>
            <div class="text-center flex-1">
              <h1 class="text-2xl font-black uppercase">Government of Sindh</h1>
              <h2 class="text-xl font-bold uppercase text-emerald-800">Finance Department</h2>
              <h3 class="text-lg font-bold">Office of the Inspector General Treasuries & Accounts</h3>
            </div>
            <div class="w-24 h-24 flex flex-col items-end">
              <span class="text-[10px] font-bold text-gray-400">RESTRICTED</span>
            </div>
          </div>

          <div class="space-y-6">
            <div class="flex justify-between font-bold text-sm">
              <span>File No: ${caseData.id}</span>
              <span>Dated: ${new Date().toLocaleDateString()}</span>
            </div>

            <section>
              <h4 class="text-lg font-black uppercase border-b mb-3">I. Case Background</h4>
              <p class="text-sm leading-relaxed">This ${caseData.type} was initiated via ${caseData.source} regarding ${caseData.officeConcerned} in ${caseData.district} district. 
              The case has been under processing for ${caseData.daysPending} days.</p>
            </section>

            <section>
              <h4 class="text-lg font-black uppercase border-b mb-3">II. Administrative Timeline</h4>
              <ul class="list-disc ml-6 space-y-1 text-sm">
                ${caseData.timeline.map(t => `<li><strong>${new Date(t.timestamp).toLocaleDateString()}:</strong> ${t.action} - ${t.remarks}</li>`).join('')}
              </ul>
            </section>

            <section>
              <h4 class="text-lg font-black uppercase border-b mb-3">III. Cooperation Status</h4>
              <p class="text-sm">The concerned office has been marked as <strong>${caseData.cooperative ? 'COOPERATIVE' : 'NON-COOPERATIVE'}</strong> based on their response patterns.</p>
              <p class="text-sm">Total Reminders Issued: ${caseData.communications.filter(c => c.type.includes('Reminder')).length}</p>
            </section>

            <section>
              <h4 class="text-lg font-black uppercase border-b mb-3">IV. Internal Findings</h4>
              <p class="whitespace-pre-wrap italic text-sm">${caseData.internalNotes || 'No specific internal notes recorded for this final report.'}</p>
            </section>

            <div class="mt-24 flex justify-between">
              <div class="text-center">
                <div class="w-48 border-b border-black mb-1"></div>
                <p class="text-[10px] font-bold uppercase">Assistant Inspector General</p>
              </div>
              <div class="text-center">
                <div class="w-48 border-b border-black mb-1"></div>
                <p class="text-[10px] font-bold uppercase">Inspector General</p>
              </div>
            </div>
          </div>

          <button onclick="window.print()" class="no-print fixed bottom-8 right-8 bg-emerald-800 text-white px-8 py-4 rounded-full font-black shadow-2xl">PRINT REPORT</button>
        </div>
        <div class="text-center mt-4 text-[10px] text-gray-400 font-bold uppercase no-print">
          Generated via IGTA Internal Dashboard • Made by Waris Nawab Panhwar
        </div>
      </body>
      </html>
    `;
    reportWindow.document.write(html);
    reportWindow.document.close();
  };

  return (
    <div className="max-w-6xl mx-auto animate-fade-in pb-20">
      <div className="mb-6 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <button onClick={onBack} className="p-2 hover:bg-white rounded-full transition-colors border shadow-sm group bg-gray-50">
            <ArrowLeft size={20} className="group-hover:text-emerald-700 transition-colors" />
          </button>
          <div>
            <h2 className="text-2xl font-black text-gray-800 tracking-tight flex items-center gap-3">
              {caseData.id}
              {caseData.slaBreach && <span className="bg-red-100 text-red-700 text-[10px] px-2 py-0.5 rounded border border-red-200 animate-pulse">SLA BREACH</span>}
            </h2>
            <div className="flex items-center gap-2 mt-1">
              <span className="text-xs font-bold text-gray-400 uppercase tracking-widest">{caseData.officeConcerned}</span>
              <span className="w-1.5 h-1.5 bg-emerald-300 rounded-full"></span>
              <span className="text-xs font-black text-emerald-700 uppercase tracking-tight">{caseData.status}</span>
            </div>
          </div>
        </div>
        <div className="flex gap-3">
          <select 
            value={caseData.status}
            onChange={(e) => updateCaseStatus(e.target.value as CaseStatus)}
            className="px-4 py-2 bg-white border-2 border-emerald-100 rounded-xl text-[10px] font-black uppercase tracking-widest hover:border-emerald-500 shadow-sm transition-all outline-none"
          >
            {CASE_STATUSES.map(s => <option key={s} value={s}>{s}</option>)}
          </select>
          <button 
            onClick={generateFinalReport}
            className="flex items-center gap-2 px-4 py-2 bg-emerald-900 text-white rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-black shadow-md transition-all active:scale-[0.98]"
          >
            <Printer size={14} /> Generate Official Report
          </button>
        </div>
      </div>

      <div className="bg-white rounded-2xl shadow-xl border border-gray-100 overflow-hidden mb-6">
        <div className="flex border-b bg-gray-50/50">
          {[
            { id: 'info', label: 'Administration', icon: ShieldAlert },
            { id: 'documents', label: 'File Records', icon: FileText },
            { id: 'reminders', label: 'Correspondence', icon: MessageSquare },
            { id: 'officers', label: 'Assigned Team', icon: Users },
            { id: 'timeline', label: 'Audit Trail', icon: History },
          ].map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`flex-1 flex items-center justify-center gap-2 py-5 text-[10px] font-black uppercase tracking-widest transition-all border-b-2 ${
                activeTab === tab.id ? 'border-emerald-600 text-emerald-900 bg-white' : 'border-transparent text-gray-400 hover:text-emerald-700 hover:bg-emerald-50/30'
              }`}
            >
              <tab.icon size={14} /> {tab.label}
            </button>
          ))}
        </div>

        <div className="p-10 min-h-[500px]">
          {activeTab === 'info' && (
            <div className="space-y-10">
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
                <div>
                  <h4 className="text-[11px] font-black text-emerald-900 uppercase tracking-[0.2em] border-b-2 border-emerald-50 pb-3 mb-6 flex items-center gap-2">
                    <FileCheck size={16} /> Workflow Profile
                  </h4>
                  <dl className="grid grid-cols-2 gap-y-8 gap-x-6">
                    <div>
                      <dt className="text-[10px] text-gray-400 font-bold uppercase mb-1">Initiation Source</dt>
                      <dd className="text-sm font-black text-gray-800">{caseData.source}</dd>
                    </div>
                    <div>
                      <dt className="text-[10px] text-gray-400 font-bold uppercase mb-1">Date of Receipt</dt>
                      <dd className="text-sm font-black text-gray-800">{caseData.dateReceived}</dd>
                    </div>
                    <div>
                      <dt className="text-[10px] text-gray-400 font-bold uppercase mb-1">District</dt>
                      <dd className="text-sm font-black text-emerald-700">{caseData.district}</dd>
                    </div>
                    <div>
                      <dt className="text-[10px] text-gray-400 font-bold uppercase mb-1">Pendency Period</dt>
                      <dd className="text-sm font-black text-red-600">{caseData.daysPending} Days</dd>
                    </div>
                    <div className="col-span-2">
                      <dt className="text-[10px] text-gray-400 font-bold uppercase mb-1">Current Status Overview</dt>
                      <dd className="text-sm font-black text-emerald-900 bg-emerald-50 p-4 rounded-xl border-2 border-emerald-100 mt-2">
                        {caseData.status}
                      </dd>
                    </div>
                  </dl>
                </div>

                <div className="space-y-6">
                  <div className="flex justify-between items-center border-b-2 border-emerald-50 pb-3">
                    <h4 className="text-[11px] font-black text-emerald-900 uppercase tracking-[0.2em] flex items-center gap-2">
                      <StickyNote size={16} /> Internal Inspector Notes
                    </h4>
                    {!isEditingNotes && (
                      <button onClick={() => setIsEditingNotes(true)} className="text-emerald-700 hover:text-emerald-900 flex items-center gap-1 text-[10px] font-black uppercase">
                        <Edit2 size={12} /> Edit
                      </button>
                    )}
                  </div>
                  
                  {isEditingNotes ? (
                    <div className="space-y-3">
                      <textarea 
                        value={notesDraft}
                        onChange={(e) => setNotesDraft(e.target.value)}
                        className="w-full h-48 p-4 rounded-xl border-2 border-emerald-100 bg-gray-50 font-medium text-sm focus:border-emerald-500 outline-none transition-all"
                        placeholder="Enter sensitive internal findings or observations..."
                      />
                      <div className="flex gap-2">
                        <button onClick={handleSaveNotes} className="flex-1 bg-emerald-700 text-white py-3 rounded-xl font-black uppercase text-[10px] tracking-widest shadow-lg">Save Observations</button>
                        <button onClick={() => { setIsEditingNotes(false); setNotesDraft(caseData.internalNotes); }} className="px-6 py-3 text-gray-400 font-black uppercase text-[10px] tracking-widest">Discard</button>
                      </div>
                    </div>
                  ) : (
                    <div className="bg-gray-50 p-6 rounded-2xl border-2 border-dashed border-gray-100 min-h-[200px]">
                      {caseData.internalNotes ? (
                        <p className="text-sm text-gray-600 leading-relaxed italic">{caseData.internalNotes}</p>
                      ) : (
                        <p className="text-sm text-gray-300 italic text-center mt-16">No internal notes recorded. Click edit to add observations.</p>
                      )}
                    </div>
                  )}
                </div>
              </div>
            </div>
          )}

          {activeTab === 'documents' && (
            <div className="space-y-8">
              <div className="flex justify-between items-center bg-emerald-50 p-6 rounded-2xl border border-emerald-100">
                <div>
                  <h3 className="text-lg font-black text-emerald-900 uppercase">File Archive</h3>
                  <p className="text-xs font-bold text-emerald-600/70 uppercase tracking-widest mt-1">AI-Assisted Processing & OCR</p>
                </div>
                <label className="bg-emerald-900 text-white px-8 py-4 rounded-2xl flex items-center gap-3 hover:bg-black cursor-pointer text-[10px] font-black uppercase tracking-[0.2em] shadow-xl transition-all active:scale-95">
                  <Plus size={20} /> {isProcessing ? 'Analyzing Document...' : 'Secure Upload PDF'}
                  <input type="file" className="hidden" accept=".pdf" onChange={handleFileUpload} disabled={isProcessing} />
                </label>
              </div>

              {caseData.documents.length === 0 && (
                <div className="text-center py-24 border-2 border-dashed border-gray-100 rounded-[2.5rem]">
                  <FileText size={64} className="mx-auto text-gray-100 mb-6" />
                  <p className="text-gray-400 font-bold uppercase tracking-widest text-xs">No documents uploaded to this case file.</p>
                </div>
              )}

              <div className="grid grid-cols-1 gap-6">
                {caseData.documents.map((doc) => (
                  <div key={doc.id} className="group border-2 rounded-[2rem] p-8 bg-white border-gray-50 hover:border-emerald-200 hover:shadow-2xl hover:shadow-emerald-900/5 transition-all relative overflow-hidden">
                    <div className="absolute top-0 right-0 w-32 h-32 bg-emerald-50 rounded-bl-full -mr-8 -mt-8 opacity-0 group-hover:opacity-100 transition-opacity"></div>
                    <div className="flex items-center justify-between mb-8 pb-8 border-b border-gray-50">
                      <div className="flex items-center gap-6">
                        <div className="w-16 h-16 bg-emerald-50 rounded-2xl flex items-center justify-center text-emerald-700">
                           <FileText size={32} />
                        </div>
                        <div>
                          <h4 className="text-xl font-black text-gray-800">{doc.fileName}</h4>
                          <div className="flex gap-3 mt-2">
                             <span className="text-[10px] font-black text-emerald-700 bg-emerald-100 px-2 py-1 rounded uppercase tracking-widest">REF: {doc.fileNumber}</span>
                             <span className="text-[10px] font-black text-gray-400 bg-gray-50 px-2 py-1 rounded uppercase tracking-widest">Authority: {doc.signingAuthority}</span>
                          </div>
                        </div>
                      </div>
                      <button className="p-3 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded-xl transition-all">
                        <Trash2 size={20} />
                      </button>
                    </div>
                    <div className="space-y-6">
                      <div className="bg-gray-50/50 p-6 rounded-2xl">
                        <p className="text-[10px] font-black text-emerald-900/40 uppercase tracking-widest mb-3 flex items-center gap-2">
                          <CheckCircle2 size={12} className="text-emerald-500" /> AI Executive Summary
                        </p>
                        <p className="text-sm text-gray-700 leading-relaxed font-medium">{doc.summary}</p>
                      </div>
                      {doc.sections && doc.sections.length > 0 && (
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                          {doc.sections.map((sec, idx) => (
                            <div key={idx} className="bg-white p-5 rounded-2xl border-2 border-emerald-50 shadow-sm hover:border-emerald-200 transition-colors">
                               <h6 className="text-[10px] font-black text-emerald-900 uppercase mb-2 flex items-center gap-2">
                                 <Building size={14} className="text-emerald-500"/> {sec.department}
                               </h6>
                               <p className="text-xs text-emerald-800/80 font-bold leading-relaxed">{sec.summary}</p>
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {activeTab === 'reminders' && (
            <div className="space-y-8">
              <div className="flex justify-between items-center mb-8 border-b-2 border-emerald-50 pb-6">
                <div>
                  <h3 className="text-xl font-black text-emerald-900 uppercase">Correspondence Tracking</h3>
                  <p className="text-xs text-gray-400 font-bold uppercase mt-1 tracking-widest">Official Reminders (Max 3 Allowed)</p>
                </div>
                <button 
                  onClick={() => setIsAddingComm(true)} 
                  disabled={caseData.communications.filter(c => c.type.includes('Reminder')).length >= 3 && !isAddingComm}
                  className="bg-emerald-800 text-white px-8 py-4 rounded-2xl flex items-center gap-3 hover:bg-black text-[10px] font-black uppercase tracking-widest shadow-xl disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <Plus size={18} /> New Correspondence
                </button>
              </div>

              {isAddingComm && (
                <form onSubmit={handleAddCommunication} className="bg-white p-8 rounded-[2rem] border-2 border-emerald-100 shadow-2xl animate-scale-up space-y-6">
                  <div className="grid grid-cols-2 gap-8">
                    <div>
                      <label className="block text-[10px] font-black text-emerald-900 uppercase mb-3 ml-1 tracking-widest">Letter Type / Classification</label>
                      <select name="type" className="w-full p-4 rounded-xl border-2 border-gray-100 text-sm font-black focus:border-emerald-500 outline-none">
                        <option value="Initial Letter">Initial Letter</option>
                        <option value="Reminder 1">Reminder 1</option>
                        <option value="Reminder 2">Reminder 2</option>
                        <option value="Final Reminder">Final Reminder (Cooperation Warning)</option>
                      </select>
                    </div>
                    <div>
                      <label className="block text-[10px] font-black text-emerald-900 uppercase mb-3 ml-1 tracking-widest">Our Reference (IGTA)</label>
                      <input name="ref" defaultValue={caseData.id} className="w-full p-4 rounded-xl border-2 border-gray-100 text-sm font-black focus:border-emerald-500 outline-none" />
                    </div>
                  </div>
                  <div>
                    <label className="block text-[10px] font-black text-emerald-900 uppercase mb-3 ml-1 tracking-widest">Target Recipients (List Separated by Comma)</label>
                    <input name="recipients" required placeholder="DAO Hyderabad, Director Accounts Sindh, etc." className="w-full p-4 rounded-xl border-2 border-gray-100 text-sm font-black focus:border-emerald-500 outline-none" />
                  </div>
                  <div className="flex gap-6 items-end">
                    <div className="flex-1">
                      <label className="block text-[10px] font-black text-emerald-900 uppercase mb-3 ml-1 tracking-widest">Compliance Deadline</label>
                      <input name="dueDate" type="date" required className="w-full p-4 rounded-xl border-2 border-gray-100 text-sm font-black focus:border-emerald-500 outline-none" />
                    </div>
                    <div className="flex-1 flex gap-3">
                      <button type="submit" className="flex-1 bg-emerald-700 text-white py-4 rounded-xl font-black uppercase text-xs tracking-widest shadow-lg hover:bg-emerald-800 transition-all">Dispatch Letter</button>
                      <button type="button" onClick={() => setIsAddingComm(false)} className="px-8 py-4 text-gray-500 font-black uppercase text-xs tracking-widest">Cancel</button>
                    </div>
                  </div>
                </form>
              )}

              <div className="space-y-6">
                {caseData.communications.map((comm) => (
                  <div key={comm.id} className="bg-white border-2 border-gray-50 rounded-[2rem] overflow-hidden shadow-sm hover:shadow-xl transition-all group">
                    <div className="p-8 flex items-center justify-between border-b border-gray-50 bg-gray-50/20 group-hover:bg-emerald-50/10 transition-colors">
                      <div className="flex items-center gap-6">
                        <div className={`w-14 h-14 rounded-2xl flex items-center justify-center ${
                          comm.type.includes('Reminder') ? 'bg-amber-100 text-amber-700' : 'bg-emerald-100 text-emerald-700'
                        }`}>
                          <MessageSquare size={24} />
                        </div>
                        <div>
                          <h4 className="text-xl font-black text-gray-800">{comm.type}</h4>
                          <div className="flex flex-wrap gap-2 mt-2">
                            {comm.recipients.map((r, i) => (
                              <span key={i} className="text-[10px] font-black text-emerald-800/60 bg-white border border-emerald-100 px-3 py-1 rounded-full uppercase tracking-widest">
                                {r}
                              </span>
                            ))}
                          </div>
                        </div>
                      </div>
                      <div className="text-right">
                        <span className={`text-[10px] font-black px-4 py-2 rounded-xl uppercase tracking-widest border-2 ${
                          comm.status === 'Awaiting' ? 'bg-amber-50 text-amber-600 border-amber-100 animate-pulse' : 
                          comm.status === 'Satisfactory' ? 'bg-emerald-50 text-emerald-700 border-emerald-100' :
                          'bg-red-50 text-red-600 border-red-100'
                        }`}>
                          {comm.status}
                        </span>
                      </div>
                    </div>
                    <div className="p-8 bg-white flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
                      <div className="flex gap-10">
                        <div>
                          <p className="text-[10px] font-black text-gray-300 uppercase tracking-widest mb-1">Issue Date</p>
                          <p className="text-sm font-black text-gray-700">{comm.dateIssued}</p>
                        </div>
                        <div>
                          <p className="text-[10px] font-black text-gray-300 uppercase tracking-widest mb-1">Due Date</p>
                          <p className="text-sm font-black text-red-700">{comm.dueDate}</p>
                        </div>
                        {comm.receivedDate && (
                          <div>
                            <p className="text-[10px] font-black text-gray-300 uppercase tracking-widest mb-1">Received Date</p>
                            <p className="text-sm font-black text-emerald-700">{comm.receivedDate}</p>
                          </div>
                        )}
                      </div>
                      
                      {comm.status === 'Awaiting' && (
                        <div className="flex gap-3">
                          <button onClick={() => evaluateResponse(comm.id, 'Satisfactory')} className="bg-emerald-700 text-white px-6 py-3 rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-black transition-all shadow-lg">Mark Satisfactory</button>
                          <button onClick={() => evaluateResponse(comm.id, 'New letter required')} className="border-2 border-amber-100 text-amber-700 px-6 py-3 rounded-xl text-[10px] font-black uppercase tracking-widest hover:bg-amber-50 transition-all">Non-Compliance</button>
                        </div>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {activeTab === 'timeline' && (
            <div className="relative pl-12 space-y-12 py-6">
              <div className="absolute left-6 top-0 bottom-0 w-1 bg-emerald-50 rounded-full"></div>
              {caseData.timeline.slice().reverse().map((entry) => (
                <div key={entry.id} className="relative group">
                  <div className="absolute -left-12 top-0 w-8 h-8 rounded-full bg-emerald-900 border-4 border-white z-10 shadow-lg group-hover:scale-125 transition-transform flex items-center justify-center">
                     <Clock size={12} className="text-white" />
                  </div>
                  <div className="bg-white border-2 border-gray-50 p-8 rounded-[2rem] shadow-sm hover:shadow-xl hover:border-emerald-100 transition-all">
                    <div className="flex justify-between items-start mb-4">
                      <h4 className="text-lg font-black text-emerald-900 uppercase tracking-tight">{entry.action}</h4>
                      <span className="text-[10px] font-black text-gray-300 uppercase tracking-widest">{new Date(entry.timestamp).toLocaleString()}</span>
                    </div>
                    {entry.oldStatus && (
                      <div className="flex items-center gap-3 mb-4 text-[10px] font-black uppercase">
                        <span className="text-gray-400 border px-2 py-0.5 rounded">{entry.oldStatus}</span>
                        <span className="text-emerald-500">→</span>
                        <span className="text-emerald-700 border border-emerald-200 px-2 py-0.5 rounded bg-emerald-50">{entry.newStatus}</span>
                      </div>
                    )}
                    <p className="text-sm text-gray-500 font-medium leading-relaxed italic border-l-4 border-emerald-50 pl-4">{entry.remarks}</p>
                  </div>
                </div>
              ))}
            </div>
          )}

          {activeTab === 'officers' && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              {caseData.officers.map((officer, i) => (
                <div key={i} className="bg-white border-2 border-gray-50 rounded-[2.5rem] p-10 shadow-sm flex items-center gap-8 group hover:border-emerald-500 transition-all relative overflow-hidden">
                   <div className="absolute -top-12 -right-12 w-32 h-32 bg-emerald-50 rounded-full opacity-20 group-hover:scale-150 transition-transform"></div>
                  <div className="w-24 h-24 bg-emerald-900 rounded-[2rem] flex items-center justify-center text-white font-black text-3xl shadow-2xl group-hover:rotate-6 transition-transform">
                    {officer.name.split(' ').map(n => n[0]).join('')}
                  </div>
                  <div className="flex-1 relative z-10">
                    <h4 className="text-2xl font-black text-gray-800">{officer.name}</h4>
                    <p className="text-xs font-black text-emerald-600 mt-1 uppercase tracking-widest">{officer.designation}</p>
                    <div className="mt-6 flex flex-col gap-2">
                       <div className="flex items-center gap-3 text-[10px] font-black text-gray-400 uppercase tracking-widest">
                         <Building size={14} className="text-emerald-500" /> {officer.department}
                       </div>
                       <div className="flex items-center gap-3 text-[10px] font-black text-gray-400 uppercase tracking-widest">
                         <ShieldAlert size={14} className="text-emerald-500" /> {officer.role} Profile
                       </div>
                    </div>
                  </div>
                </div>
              ))}
              <button className="bg-gray-50 border-4 border-dashed border-gray-100 rounded-[2.5rem] p-10 flex flex-col items-center justify-center group hover:bg-emerald-50 hover:border-emerald-200 transition-all">
                <Plus size={48} className="text-gray-200 group-hover:text-emerald-500 mb-4 transition-colors" />
                <p className="text-[10px] font-black text-gray-300 group-hover:text-emerald-700 uppercase tracking-widest">Assign Supporting Officer</p>
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default CaseDetails;
